settings:
  name: ONTAP tools for VMware vSphere 10.0
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar: 
  entries:
    - title: ONTAP tools for VMware vSphere 10.0 docs
      url: /index.html
    - title: Release notes
      url: /release_notes.html
    - section: concepts
    - section: deploy
    - section: configure
    - section: manage
    - section: migrate
    - title: Legal notices
      url: /legal-notices.html
