---
permalink: manage/discovery.html
sidebar: sidebar
keywords:
summary: 'Discovery interval can be configured as part of the configuration map.'
---
= Discovery 
:icons: font
:imagesdir: ../media/

[.lead]
Discovery interval can be configured as part of the configuration map. Scheduled discovery runs for every 60 mins. The API given here is to run the discovery on demand for a given storage backend which is added in the local scope. 

Use the following API to run discovery:
----
POST
/virtualization/api/v1/vcenters/{vcguid}/storage-backends/{id}/discovery-jobs
----

[NOTE]
--
See link:../configure/onboard_svm.html[Onboard storage backend (SVM or Cluster)] section and get ID from post storage backend API response.
--

Discovery from this API endpoint is supported only for local scoped storage backends and not for the global scoped storage backends.
If the storage backend type is cluster, discovery implicitly runs for the child svms.
If the storage backend type is svm, discovery only runs for the selected svm.

Example:

To run discovery on a storage backend specified by ID
----
POST
/api/v1/vcenters/3fa85f64-5717-4562-b3fc-2c963f66afa6/storage-backends/74e85f64-5717-4562-b3fc-2c963f669dde/discovery-jobs
----

You need to pass x-auth for the API. You can generate this x-auth from the new API added under Auth in Swagger.
----
/virtualization/api/v1/auth/vcenter-login
----
